#todo: change folder structure to the one from
#  https://trash-guides.info/File-and-Folder-Structure/How-to-set-up/Docker/
# link data/torrents for transmission and data for Starr Apps

services:
#  for series
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - mediarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config/mediarr/sonarr:/config
      - myMedia:/home/media
      - myDlFolders:/home/downloads
    depends_on:
      - transmission
      - jackett

# for movies
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - mediarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config/mediarr/radarr:/config
      - myMedia:/home/media
      - myDlFolders:/home/downloads
    depends_on:
      - transmission
      - jackett

# Subs (or just get hardsubbed stuff from nyaa.si)
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    networks:
      - mediarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config/mediarr/bazarr:/config
      - myMedia:/home/media
      - myDlFolders:/home/downloads
    depends_on:
      - sonarr
      - radarr

# Trackers
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    networks:
      - mediarr
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config/mediarr/jackett:/config
      - myMedia:/home/media
      - myDlFolders:/home/downloads

  # maybe replace with qbit later
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    networks:
      - mediarr
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config/mediarr/transmission:/config
      - myMedia:/home/media
      - myDlFolders:/home/downloads

# MediaPlayer - not sure if i wanna use this
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - mediarr
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config/mediarr/jellyfin:/config
      - myMedia:/home/media
      - myDlFolders:/home/downloads
    depends_on:
      - sonarr
      - radarr

networks:
  mediarr:
    driver: bridge

volumes:
  myData:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
